//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1
//and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
let arr = [];
function f(n) {
  arr[0] = 1;
  arr[1] = 2;
  for (let i = 2; i < n; i++) {
    arr[i] = arr[i - 2] + arr[i - 1];
  }
}
f(40);
//console.log(arr);

function fR(n) {
  if (n <= 1) {
    return n;
  }

  return fR(n - 1) + fR(n - 2);
}

console.log(fR(40));
